import fs from 'fs';

let content = fs.readFileSync('src/App.tsx', 'utf8');

// 1. the Dynamic Background Elements:
const regexBg = /\{\/\* Dynamic Background Elements for more vibrant feel \*\/\}[\s\S]*?<\/div>/;

const bgElementsNew = `{/* Simplified Background Elements for Performance */}
      <div className="fixed inset-0 overflow-hidden pointer-events-none z-0">
        <div className="absolute top-0 inset-x-0 h-full bg-gradient-to-br from-[#004b87]/5 via-[#3b82f6]/5 to-[#f58220]/5" />
        <div className="hidden md:block absolute -top-[20%] -left-[20%] w-[80vw] h-[80vw] rounded-full bg-[radial-gradient(circle,rgba(0,242,255,0.1)_0%,transparent_70%)] opacity-50 relative z-0" />
        <div className="hidden md:block absolute top-[10%] -right-[20%] w-[80vw] h-[80vw] rounded-full bg-[radial-gradient(circle,rgba(0,75,135,0.1)_0%,transparent_70%)] opacity-50 relative z-0" />
        <div className="absolute inset-0 bg-[url('https://www.transparenttextures.com/patterns/carbon-fibre.png')] opacity-[0.02] pointer-events-none mix-blend-normal" />
      </div>`;

content = content.replace(regexBg, bgElementsNew);

// There are other decorative elements in "Quienes Somos":
// mix-blend-screen and animate blob
content = content.replace(/className="absolute top-0 right-0 md:right-10 w-48 h-48 md:w-64 md:h-64 bg-\[radial-gradient\(circle,rgba\(245,130,32,0\.25\)_0%,transparent_70%\)\] rounded-full pointer-events-none mix-blend-screen"/g, 'className="hidden md:block absolute top-0 right-0 md:right-10 w-48 h-48 md:w-64 md:h-64 bg-[radial-gradient(circle,rgba(245,130,32,0.15)_0%,transparent_70%)] rounded-full pointer-events-none"');

content = content.replace(/className="absolute bottom-0 left-0 md:left-10 w-56 h-56 md:w-72 md:h-72 bg-\[radial-gradient\(circle,rgba\(0,242,255,0\.2\)_0%,transparent_70%\)\] rounded-full pointer-events-none mix-blend-screen"/g, 'className="hidden md:block absolute bottom-0 left-0 md:left-10 w-56 h-56 md:w-72 md:h-72 bg-[radial-gradient(circle,rgba(0,242,255,0.1)_0%,transparent_70%)] rounded-full pointer-events-none"');

// Fix Fortalezas Modal not scrolling effectively on mobile.
// flex-1 overflow-y-auto is good, but if parent has max-h-[90vh], it can sometimes get cut off or scroll gets locked by iOS inside fixed containers dynamically generated by Framer Motion if there's will-change.
content = content.replace(/max-h-\[90vh\] flex flex-col will-change-transform"/, 'max-h-[90vh] md:max-h-[85vh] h-full md:h-auto flex flex-col"');

fs.writeFileSync('src/App.tsx', content);
console.log('Fixed performance issues');
