const CATEGORY_IMAGES: Record<string, string[]> = {
  'pisos-comerciales': [
    'https://i.ibb.co/k2kd5Tq3/1.webp',
    'https://i.ibb.co/MyCd48Rp/2.webp',
    'https://i.ibb.co/Y7DtBMpK/3.webp',
    'https://i.ibb.co/YgyNNbX/4.webp',
    'https://i.ibb.co/9H2ptfZb/5.webp',
    'https://i.ibb.co/TBP4QnHn/6.webp',
    'https://i.ibb.co/xS9xFkL3/7.webp',
    'https://i.ibb.co/tPvYRmHJ/8.webp',
    'https://i.ibb.co/Z1LJFY1H/9.webp',
    'https://i.ibb.co/bM9vVFZ5/10.webp',
    'https://i.ibb.co/8D8q7wPB/11.webp',
    'https://i.ibb.co/R4hW8rc6/12.webp',
    'https://i.ibb.co/9HbJ56vW/13.webp',
    'https://i.ibb.co/FbX3LMcy/14.webp',
    'https://i.ibb.co/n8Pjkcx2/15.webp',
    'https://i.ibb.co/NghF8cwG/16.webp',
    'https://i.ibb.co/FbH1yg1s/17.webp',
    'https://i.ibb.co/RTs1j4RB/18.webp',
    'https://i.ibb.co/CsHMjMXD/19.webp',
    'https://i.ibb.co/FbKpdtpK/20.webp',
    'https://i.ibb.co/TDPsyt5x/21.webp',
    'https://i.ibb.co/Kzc2RG1K/22.webp',
    'https://i.ibb.co/p6GSWHBp/23.webp',
    'https://i.ibb.co/NdGkCC4t/24.webp',
    'https://i.ibb.co/cKL202G3/25.webp',
    'https://i.ibb.co/9kVrm9gm/26.webp',
    'https://i.ibb.co/jP0pZtvc/27.webp',
  ],
  'pisos-epoxicos': [
    'https://i.ibb.co/1GC1X7dw/1.webp',
    'https://i.ibb.co/NdSJ4jQ2/2.webp',
    'https://i.ibb.co/KprXnzG6/3.webp',
    'https://i.ibb.co/k6D5Y3Ff/4.webp',
    'https://i.ibb.co/VWZ1r2mL/5.webp',
    'https://i.ibb.co/8LWgjfq5/6.webp',
  ],
  'acabados-alta-gama': [
    'https://i.ibb.co/gL2DGHpQ/1.webp',
    'https://i.ibb.co/mFbHwxFm/2.webp',
    'https://i.ibb.co/8LCHLwmd/3.webp',
    'https://i.ibb.co/1JBxjHyD/4.webp',
    'https://i.ibb.co/KcJDDSZV/5.webp',
    'https://i.ibb.co/DDfP4Q1w/6.webp',
    'https://i.ibb.co/twc09Bjm/7.webp',
    'https://i.ibb.co/tM8qgScG/8.webp',
    'https://i.ibb.co/Kx25KY5y/9.webp',
    'https://i.ibb.co/RT9qYZm3/10.webp',
    'https://i.ibb.co/GQGXp9cZ/11.webp',
    'https://i.ibb.co/Xrp563Hs/12.webp',
    'https://i.ibb.co/XrnnVtW6/13.webp',
    'https://i.ibb.co/WpPbJRjN/14.webp',
    'https://i.ibb.co/MyGGRF9k/15.webp',
    'https://i.ibb.co/0VGDprny/16.webp',
    'https://i.ibb.co/CKSFp1GF/17.webp',
    'https://i.ibb.co/7tFyBWfd/18.webp',
    'https://i.ibb.co/Z6Js1Xwn/19.webp',
    'https://i.ibb.co/0VC65bkt/20.webp',
    'https://i.ibb.co/KpqTs6w0/21.webp',
    'https://i.ibb.co/KxLw7J3h/22.webp',
    'https://i.ibb.co/5CFc54d/23.webp',
    'https://i.ibb.co/rGv96jGW/24.webp',
  ],
  'reparacion-concreto': [
    'https://i.ibb.co/fGVGy4b9/1.webp',
    'https://i.ibb.co/zVnx0W0Z/2.webp',
    'https://i.ibb.co/67SQKvF7/3.webp',
    'https://i.ibb.co/zhHKhZVg/4.webp',
    'https://i.ibb.co/k2kyYdz7/5.webp',
    'https://i.ibb.co/1Jqf9TT1/6.webp',
  ],
  'impermeabilizacion': [
    'https://i.ibb.co/0RNmfQns/9.webp',
    'https://i.ibb.co/pvp2trW3/8.webp',
    'https://i.ibb.co/35Rq2ScH/7.webp',
    'https://i.ibb.co/CpRF4Rd6/6.webp',
    'https://i.ibb.co/7JZHz93R/5.webp',
    'https://i.ibb.co/0yKJGZCt/4.webp',
    'https://i.ibb.co/6cS8swG4/3.webp',
    'https://i.ibb.co/jpP5Zm5/2.webp',
    'https://i.ibb.co/MkFXfB5n/1.webp',
  ],
  'pinturas-especiales': [
    'https://i.ibb.co/VcGSBzLj/1.webp',
    'https://i.ibb.co/Qv9dKtp1/2.webp',
    'https://i.ibb.co/gLfLtCFb/3.webp',
    'https://i.ibb.co/9HqQbm4V/4.webp',
    'https://i.ibb.co/NgWfLQ7v/5.webp',
    'https://i.ibb.co/27RKHT9b/6.webp',
    'https://i.ibb.co/zVfBkPLY/7.webp',
    'https://i.ibb.co/pv30rdk5/8.webp',
    'https://i.ibb.co/kVWFfkLB/9.webp',
    'https://i.ibb.co/Swj96xSR/10.webp',
    'https://i.ibb.co/XZstj9X8/11.webp',
    'https://i.ibb.co/9kjSVR1J/12.webp',
    'https://i.ibb.co/VYfYvYnH/13.webp',
    'https://i.ibb.co/NnsPVdcc/14.webp',
    'https://i.ibb.co/pj9m3BvP/15.webp',
    'https://i.ibb.co/dwhRr1N1/16.webp',
    'https://i.ibb.co/Nnb2FwX5/17.webp',
  ],
  'sistema-cortafuegos': [
    'https://i.ibb.co/PzCspYpW/1.webp',
    'https://i.ibb.co/WNW00vZ9/2.webp',
    'https://i.ibb.co/mFPQYt2P/3.webp',
    'https://i.ibb.co/jZ670wHK/4.webp',
    'https://i.ibb.co/SwtYMjky/5.webp',
    'https://i.ibb.co/WWJHncw8/6.webp',
    'https://i.ibb.co/RkLvP9hp/7.webp',
    'https://i.ibb.co/bgqhqCDr/8.webp',
    'https://i.ibb.co/NgD5M7Px/9.webp',
    'https://i.ibb.co/twZ1XRmr/10.webp',
    'https://i.ibb.co/svHxtQbK/11.webp',
    'https://i.ibb.co/8479DTzV/12.webp',
  ],
  'aislamiento': [
    'https://i.ibb.co/Mk2kr7Vp/1.webp',
  ],
};

const ALL_IMAGES = CATEGORIES.flatMap(cat => {
  const catImages = CATEGORY_IMAGES[cat.id] || [];
  return catImages.map((url, i) => ({
    id: `${cat.id}-${i + 1}`,
    categoryId: cat.id,
    categoryTitle: cat.title,
    url: url,
    title: `${cat.title} - Proyecto ${i + 1}`,
  }));
});
